### ISSUE TITLE
Battery level status too low

### ISSUE THREAD

**Issue by kernie66** [jeppesens/homebridge-glue#11]
Thanks for the great plugin. I just have one issue. 

It seems like the battery level reported by the Glue app differs from the level in the plugin. Today for example, the plugin reports 16% while the app reports 34%. Perhaps the value returned by Glue isn't just a linear percentage.

**Comment by jeppesens** [comment]
As you probably know, there is no documentation supplied by Glue. 

From what I remember. There's two battery levels supplied by Glue. One of the values is always available the other one is not always available. In this case I opted for the lower level that is always present rather than the higher not always available level. 

PRs with improvements are welcome!

**Comment by jeppesens** [comment]
This should now be resolved with using the new api from Glue.
